
path: H:\Utm\Anul2\Sem4\Tomato\tomato
train: train\images
val: train\images

nc: 10
names: ['Bacterial Spot', 'Early Blight', 'Healthy', 'Late Blight', 'Leaf Mold', 'Leaf_Miner', 'Mosaic Virus', 'Septoria', 'Spider Mites', 'Yellow Leaf Curl Virus']